version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/tasktracker
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - '5173:5173'
    depends_on:
      - server

volumes:
  mongo-data: